name: 'salesforce_integration_tests'
version: '0.3.0'
config-version: 2

profile: 'integration_tests'

vars:
  salesforce:
    account: "{{ ref('stg_salesforce__account') }}"
    opportunity: "{{ ref('stg_salesforce__opportunity') }}"
    user: "{{ ref('stg_salesforce__user') }}"
    user_role: "{{ ref('stg_salesforce__user_role') }}"

  salesforce_source:
    salesforce_database: raw
    salesforce_schema: raw_fivetran_salesforce


clean-targets:
    - target
    - dbt_modules
